import React from 'react'
import { useGSAP } from '@gsap/react';
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LaptopTable(props) {
  const { nodes, materials } = useGLTF('/models/pc_setup_with_gaming_chair.glb')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk1_blinn2_0.geometry}
            material={materials.blinn2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk1_Masa_Ana_0.geometry}
            material={materials.Masa_Ana}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk1_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk1_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk2_blinn2_0.geometry}
            material={materials.blinn2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk2_Masa_Ana_0.geometry}
            material={materials.Masa_Ana}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk2_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk2_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel_Side_Main_0.geometry}
            material={materials.Side_Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel_Side_Frame_0.geometry}
            material={materials.Side_Frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel2_Side_Main_0.geometry}
            material={materials.Side_Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel2_Side_Frame_0.geometry}
            material={materials.Side_Frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel3_Side_Main_0.geometry}
            material={materials.Side_Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Panel3_Side_Frame_0.geometry}
            material={materials.Side_Frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe6_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe5_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe4_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe3_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe2_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pipe_Table_Pipe_0.geometry}
            material={materials.Table_Pipe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel4_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel4_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel3_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel3_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel2_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel2_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Monitor_Monitor_Frame_0.geometry}
            material={materials.Monitor_Frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Monitor_wallpaperScreen_0.geometry}
            material={materials.wallpaperScreen}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cable_CableColor_0.geometry}
            material={materials.CableColor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mouse_MouseMaterial_0.geometry}
            material={materials.MouseMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Keyboard_Keyboard_Main_0.geometry}
            material={materials.Keyboard_Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Keyboard_Keyboard_Keys_0.geometry}
            material={materials.Keyboard_Keys}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Case_PC_kasa_0.geometry}
            material={materials.PC_kasa}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Case_PC_kasa_0_1.geometry}
            material={materials.PC_kasa}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Case_PC_powerButton_0.geometry}
            material={materials.PC_powerButton}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Case_PC_PowerButtonColor_0.geometry}
            material={materials.PC_PowerButtonColor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Case_PC_USB_grey_0.geometry}
            material={materials.PC_USB_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Ayak_Chair_Ayak_0.geometry}
            material={materials.Chair_Ayak}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Piston_Chair_Ayak_0.geometry}
            material={materials.Chair_Ayak}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Piston_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_PistonUst_Chair_Ayak_0.geometry}
            material={materials.Chair_Ayak}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Chair_Plastic_0.geometry}
            material={materials.Chair_Plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Chair_Fabric_0.geometry}
            material={materials.Chair_Fabric}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Koltuk_Chair_Red_0.geometry}
            material={materials.Chair_Red}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker6_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker6_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker5_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker5_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker9_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker9_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker8_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker8_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker7_Teker_0.geometry}
            material={materials.Teker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teker7_Teker_Metal_0.geometry}
            material={materials.Teker_Metal}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pc_setup_with_gaming_chair.glb')
